// <auto-generated />
namespace FoodPalace.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addProductsgg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addProductsgg));
        
        string IMigrationMetadata.Id
        {
            get { return "201812180706116_addProductsgg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
